name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15.0.2
        java-package: jdk
    - name: Install Ghidra
      run: |
        wget https://ghidra-sre.org/ghidra_9.2.2_PUBLIC_20201229.zip
        sudo unzip ghidra_9.2.2_PUBLIC_20201229.zip /opt
    - name: Build
      run: gradle -PGHIDRA_INSTALL_DIR=/opt/ghidra_9.2.2_PUBLIC_20201229
    - name: Upload JAR
      uses: actions/upload-artifact@v2.2.0
      with:
        name: JAR
        path: build/libs/ghidra-iboot.jar
